[package]
name = "egui-122-checkbox-functionality"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
eframe = "0.24.0" # Gives us egui, epi and web+native backends
# rand = "0.8"

